[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "Asia/Tokyo"

[context.production.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENV = "production"
